import fs from "node:fs";
import path from "node:path";

export function makePdf(lines: string[]): Buffer {
	const escape = (text: string) => text.replace(/[\\()]/g, (char) => `\\${char}`);
	const content = [
		"BT /F1 14 Tf 72 740 Td 18 TL",
		...lines.map((line, index) => `${index ? "T* " : ""}(${escape(line)}) Tj`),
		"ET",
	].join("\n");
	const objects = [
		"<< /Type /Catalog /Pages 2 0 R >>",
		"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
		`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,
		"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
	];
	let body = "%PDF-1.4\n";
	const offsets: number[] = [];
	objects.forEach((object, index) => {
		offsets.push(Buffer.byteLength(body));
		body += `${index + 1} 0 obj\n${object}\nendobj\n`;
	});
	const xref = Buffer.byteLength(body);
	body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
	body += offsets.map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("");
	body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
	return Buffer.from(body);
}

export function writePdfs(dir: string, names: string[], lines: string[] = defaultLines()): string[] {
	fs.mkdirSync(dir, { recursive: true });
	return names.map((name) => {
		const file = path.join(dir, name.endsWith(".pdf") ? name : `${name}.pdf`);
		fs.writeFileSync(file, makePdf([`${path.basename(file, ".pdf")}`, ...lines]));
		return file;
	});
}

function defaultLines(): string[] {
	return [
		"Wikify end-to-end test document.",
		"This one-page PDF is generated by the Playwright suite.",
		"It has a clean text layer, so it parses quickly.",
	];
}
